---
# tasks file for lb-tier
- name: install haproxy
  package:
    name: haproxy
    state: present
- name: enable haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
- name: configure haproxy and restart
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
